spring.application.name=studyBuddy

spring.datasource.url=jdbc:mysql://localhost:3306/study_buddy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2000Jd**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/org5rgqf/oauth2/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/org5rgqf/oauth2/jwks





# springbackAPI
# back client ID :- cd8a06b9-cf68-4589-b73d-d88826b42889
# tenent :- studentlearnsuppoeter
# tenentId:- 172eddcb-f42a-4814-804e-6cf57f9061b8
# app ID URI :- https://studentlearnsuppoeter.onmicrosoft.com/cd8a06b9-cf68-4589-b73d-d88826b42889

#reacetClientAPP
# B2C_1_signup
#client secret:- mpC8Q~Y7LD7dCKoUNWB7vUbcSEG2eSU2jXm3eco6
#client client ID:- b9266c9a-5d66-447c-a26a-07251857e4d1