spring.application.name=studyBuddy

spring.datasource.url=jdbc:mysql://localhost:3306/study_buddy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2000Jd**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.asgardeo.io/t/org5rgqf/oauth2/token
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://api.asgardeo.io/t/org5rgqf/oauth2/jwks

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://studtsupportdemo.b2clogin.com/b90a36ed-cdb2-47dd-a129-be8bf242a141/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://studtsupportdemo.b2clogin.com/studtsupportdemo.onmicrosoft.com/b2c_1_study/discovery/v2.0/keys



